name = "MulticolorRamsey"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MulticolorRamsey"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[require]]
name = "ExponentialRamsey"
git = "https://github.com/ooovi/ExponentialRamsey.git"
rev = "version-bump"

[[lean_lib]]
name = "MulticolorRamsey"
